### ISSUE TITLE
Страница автора: отображаются одновременно кнопки "В избранное" и "Из избранного"

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#103]
При переходе на страницу, содержащую все материалы конкретного автора, одновременно отображаются кнопки "В избранное" и "Из избранного", должна отображаться только одна, в  зависимости от наличия конкретного материала в Избранном
http://joxi.ru/1A590xkSzWMJAE скрин, http://185.22.63.140/author/admin/page1 пример ссылки

**Comment by gtament** [comment]
Пофикшено
