### ISSUE TITLE
Главная страница: не отображаются теги материала

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#30]
На главной странице не отображаются теги статьи

**Comment by dunknown** [comment]
В ТЗ сказано, что теги должны отображатся на странице материала.

**Comment by IKeiran** [comment]
А дай-ка ссылочку на страница материала

**Comment by dunknown** [comment]
Страница материала сейчас в разработке

**Comment by dunknown** [comment]
Вообще я не против теги впихнуть и на все остальные страницы.

**Comment by gtament** [comment]
Вообще с текущим дизайном отображать теги на главной не кошерно будет. Так что в таком виде я бы от фичи отказался
