### ISSUE TITLE
Добавление материала: некорректный редирект

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#36]
Как автор, после добавления материала я хотел бы видеть страницу материала такой, как ее будет видеть читатель. 

В текущей реализации после добавления материала автор перенаправляется на главную страницу, что не корректно, в связи с тем, что сам автор не может отсылать свои материалы на главную сайта. 

Шаги по воспроизведению: 
1) Войти в систему с ролью "Автор"
2) Добавить новый материал 
**Ожидаемый результат**: автор перенаправляется на страницу своего материала
**Фактический результат**: автор перенаправляется на главную страницу сайта.

**Comment by dunknown** [comment]
Юра, сделай при посте материала редирект на /material/{id}

**Comment by gtament** [comment]
Done
