### ISSUE TITLE
Добавление материала: сделать служебный текст в поле ввода неактивным

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#37]
Как автор, при добавлении материала я хочу вводить текст статьи в чистое поле ввода, чтобы при получении фокуса весь служебный текст исчезал

В текущей реализации перед добавлением каждого материала необходимо предварительно удалить служебный текст _"Введите текст материала здесь…"_ 
[скриншот](http://dl1.joxi.net/drive/0003/2742/244406/150527/d220713dc3.jpg), 
[пример](http://dl2.joxi.net/drive/0003/2742/244406/150527/c29b81063f.jpg), при получении фокуса текст исчезает.

**Comment by dunknown** [comment]
Не будет исправлено.
