### ISSUE TITLE
WYSWYG редактор: пустое поле справа от пиктограммки добавления изображения

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#63]
При добавлении и редактировании материала появляется пустое нефункциональное справа от пиктограммки добавления изображения, из-за чего плывет верстка редактора.  После клика  по нему поле скрывается, и добавление изображения осуществляется только по повторному клику. 

Предсостояние: 
1) пользователь залогинен под ролью выше читателя
Шаги по воспроизведению: 
1) Открыть страницу добавления материала
2) Нажать на пустую область возле пиктограммки добавления изображения
Фактический результат: пустая облась возле пиктограммки скроется (см. скриншот) 
Ожидаемый результат: отсутствие пустых полей в меню редактора, открытие диалога для добавления изображения

Скрин: http://dl1.joxi.net/drive/0003/2742/244406/150612/f04e4a1d09.jpg

**Comment by dunknown** [comment]
Встречалось, рандомно. Кажется исправлено
