### ISSUE TITLE
Добавление материала: отсутствует уведомление о потере данных при уходе со страницы

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#64]
При случайном переходе со страницы добавления (редактирования) материала отсутствует уведомление о потере данных в случае, если материал не был сохранен. 

Предсостояние: 
Пользователь вошел в систему с ролью, позволяющей добавлять/редактировать материал,
Шаги по воспроизведению: 
1) Открыть страницу добавления материала
2) Изменить текст статьи
3) Нажать на любую кнопку меню, перенаправляющую пользователя. 
Фактический результат:  пользователь будет перенаправлен на выбранную страницу
Ожидаемый результат: уведомление о том, что несохраненные данные дубут потеряны

(!) такая же ситуация при редактировании материала.

**Comment by dunknown** [comment]
Исправлено
