### ISSUE TITLE
Избранное: при удалении материала из Избранного не происходит обновление контента страницы

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#65]
При удалении материала из Избранного не происходит обновление контента страницы, материал  остается на странице до ее принудительного обновления. 
Ожидаемый результат - удаление страницы аналогично Главной сайта

**Comment by dunknown** [comment]
Исправлено

**Comment by IKeiran** [comment]
При нажатии "В архив" или "На главную" исчезновения контента не должно быть, только тзменение названия кнопок

**Comment by dunknown** [comment]
ОК, исправлю

**Comment by dunknown** [comment]
> При нажатии "В архив" или "На главную" исчезновения контента не должно быть, только изменение названия кнопок

Создал отдельный issue. Это закрыто
