### ISSUE TITLE
Модерация: взять в работу должна перенаправлять на страницу выбранного материала

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#66]
Как редактор, я бы хотел удобной работы с материалами, т.е.:
1) открыть список ожидающих модерацию материалов
2) выбрать материал для модерирования
3) при нажатии на "Взять в работу" получить открывшийся материал, с которым я мог бы сразу ознакомиться и одобрить или отклонить 

Сейчас для того, чтобы взять материал в работу, я должен выполнить следующие действия: 
1) Открыть список материалов, ожидающих модерацию
2) Нажать на кнопку "Взять в работу"
3) Перейти  в раздел "Модерировать"
4) Повторно найти нужный материал
5) Нажать "Одобрить"
Таким образом, нужно выполнить 3 лишних действия.

**Comment by dunknown** [comment]
ИМХО, лучше сначала взять в работу несколько материалов, не уходя со страницы "Ожидают модерации", а затем работать с ними на странице "Модерировать"
