### ISSUE TITLE
WYSWYG редактор: при увеличении отступа меняется размер шрифта

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#67]
Предсостояние: 
1) пользователь залогинен в систему с правами, достаточными для добавления материала
2) открыта страница добавления материала
Шаги по воспроизведению: 
1) написать любой текст
2) увеличить отступ
Ожидаемый результат: размер текста не изменится
Фактический результат: размер текста увеличивается

**Comment by dunknown** [comment]
Исправлено
