### ISSUE TITLE
Добавление материала: ошибка Whitelabel Error Page после добавленния материалов автором

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#68]
После добавления материалов **Автором** сервер выдает Whitelabel Error Page

Шаги по воспроизведению: 
1) Залогиниться в систему с ролью **Автор**
2) Добавить новый материал
Ожидаемый результат: Сообщение о том, что материал отправлен на модерацию
Фактический результат: ошибка Whitelabel Error Page
Скриншот: http://dl2.joxi.net/drive/0003/2742/244406/150612/ebd76309cf.jpg

**Comment by dunknown** [comment]
ИМХО, автор не имеет права просматривать материал, пока тот находиться в модерации и видеть промежуточные изменения, сделанные модератором. Сделаю так: админ и редактор после отправки материала будут попадать на страницу материала, так как имеют право взять его себе в модерацию (что сейчас и происходит), обычный автор будет перенаправляться на главную (вместо текущей ошибки).

**Comment by IKeiran** [comment]
Просматривать может, почему нет? Правки - да, вносить не имеет права, раз сдал работу. 
Но по реализации это не в приоритете, по релиректу согласен

**Comment by dunknown** [comment]
Не может просматривать, потому что модератор пока работает над материалом может там оставлять какие-то служебные пометки для себя или еще что-то в этом роде. Не стоит автору следить за его работой, по крайней мере никогда не видел такого нигде.

**Comment by dunknown** [comment]
Сделано
