### ISSUE TITLE
Добавление материала: заголовок без пробелов ломает верстку

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#69]
Предсостояние: 
1) Пользователь вошел в систему с ролью "Автор"
2) Открыта страница добавления материалов
Шаги по возпроизведению: 
1) Добавить максимальную длину заголовка (100 символов) без пробелов
2) Добавить любой корректный текст и тэги
3) Нажать "Добавить"
Фактический результат: заголовок выходит за пределы статьи, ломая верстку
Ожидаемый результат: заголовок принудительно переносится, сохраняя верстку
Скриншот: http://dl2.joxi.net/drive/0003/2742/244406/150612/307fbb767b.jpg

**Comment by dunknown** [comment]
Исправлено
