### ISSUE TITLE
<cut> в поле текста при редактировании

### ISSUE THREAD

**Issue by freelanseod** [dunknown/NIAT_CMS#78]
При попытке автором редактировать материал из черновиков добавляется в поле текста <cut>
![1](https://cloud.githubusercontent.com/assets/6490933/8150264/ad21d90e-12eb-11e5-8fb2-148457052f0f.jpg)

**Comment by gtament** [comment]
Это не баг, это фича))

**Comment by dunknown** [comment]
Это баг. Кат появляется, даже если пользователь его не ставил (mainText - пустая строка). Но в контроллерах проверка mainText не на пустую строку, а на null. Назначаю тебе, сделай проверку на пустую строку.
