### ISSUE TITLE
Страница модерации материала доступна по прямой ссылке

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#91]
Неавторизированный пользователь может получить доступ к неопубликованным материалам по прямой ссылке http://185.22.63.140/modertasks/page1.
Такая же ситуация для ролей читатель и автор

**Comment by IKeiran** [comment]
а где красивое сообщение об ошибке? 
И, пожалуйста, не закрывай, а перенаправляй на меня для проверки

**Comment by gtament** [comment]
Баг пофикшен? Пофикшен. Перед коммитом я проверяю на локалке лично. Хочешь что-то - это фичреквест уже будет, а не баг - отдельным issue

**Comment by gtament** [comment]
Теперь и на серваке

**Comment by IKeiran** [comment]
Баг пофикшен когда он на сарваке исправлен и перепроверен, что его исправление не повлекло за собой новых багов.

**Comment by gtament** [comment]
Полностью согласен
