### ISSUE TITLE
Архив: невозможно добавить материал на главную

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#92]
При попытке добавить материал на Главную страницу из архива возникает ошибка "Не удалось отправить материал на главную"
Шаги по воспроизведению: 
1) Войти в систему с ролью Администратор
2) Открыть страницу Архива 
3) Нажать "На главную"

Ожидаемый результат: материал будет добавлен на главную страницу
Фактический результат: сообщение об ошибке  "Не удалось отправить материал на главную"

Та же ситуация наблюдается при попытке добавить материал на главную со страницы самого материала.

**Comment by IKeiran** [comment]
та же ситуация при отправке материала в Архив. 
При удалении материала так же возникает ошибка. Думаю, источник бед один, поэтому в одно ишью кидаю.

**Comment by gtament** [comment]
Пофикшено
