### ISSUE TITLE
Можно добавить материал с точно таким же заголовком

### ISSUE THREAD

**Issue by freelanseod** [dunknown/NIAT_CMS#93]
![2](https://cloud.githubusercontent.com/assets/6490933/8202130/c5a5d228-14df-11e5-9c36-098ab0a8ab1c.jpg)
![3](https://cloud.githubusercontent.com/assets/6490933/8202131/c5bfa0a4-14df-11e5-96a5-ebf3cbb0f2f7.jpg)

**Comment by gtament** [comment]
Не баг

**Comment by IKeiran** [comment]
Баг в чистом виде. То, что он не будет фиксится - другой вопрос
