### ISSUE TITLE
невозможно зафичерить заголовок любого материала на главной кроме первого

### ISSUE THREAD

**Issue by freelanseod** [dunknown/NIAT_CMS#95]
идет выдача ошибки, что нельзя
далее, если зафичерить первый материал, потом поменять местами его со вторым, то зафичерить первый материал на 2м месте можно, впрочем как и расфичерить
и после всех этих действий нельзя удалить материал с главной страницы

**Comment by gtament** [comment]
Не воспроизводится. У меня все работает. Скорее всего одновременно редактировали главную
