### ISSUE TITLE
Корректор: по прямой ссылке доступна страница черновиков

### ISSUE THREAD

**Issue by IKeiran** [dunknown/NIAT_CMS#97]
Корректор при переходе на страницу черновиков по прямой ссылке http://185.22.63.140/drafts/page1 пользователь видит список своих статей. Для теста можно воспользоваться логином IKeiran паролем qwerty123
Ожидаемый результат - если на страницу нельзя попасть через меню сайта, доступ должен быть закрыт, т.е. при переходе пользователь должен получить 403 ошибку.

**Comment by gtament** [comment]
Не понял, почему корректор не должен видеть свои черновики?

**Comment by IKeiran** [comment]
потому что по интрефейсу у него опции добавления материала нет
