### ISSUE TITLE
не удаляется материал из архива

### ISSUE THREAD

**Issue by freelanseod** [dunknown/NIAT_CMS#99]
Роль-администратор
шаги:
1)переход в архив
2)попытка удаления материала с заголовком "ааааааааааааааа"
3)подтверждаем удаление материала
и тут выходит сообщение о том, что его нельзя удалить

**Comment by IKeiran** [comment]
на других ролях ситуация такая же. На совместную работу не похоже - после обновления страница не меняется

**Comment by dunknown** [comment]
вроде пофикшено
